fb/urls.py
from django.urls import path
from . import views
app_name='fb'

urlpatterns = [
    path('',views.home, name='home'),
    path('/page',views.page, name='page'),
    path('/forget',views.forget, name='forget'),
        path('/craa',views.craa, name='craa')
   
]

fbdemo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fb',include('fb.urls'))
]

fb/models.py
from django.db import models

# Create your models here.

fb/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render (request, 'fb-templates/home.html')

def page(request):
    return render (request, 'fb-templates/page.html')

def forget(request):
    return render (request, 'fb-templates/forget.html')   

def craa(request):
    return render (request, 'fb-templates/craa.html')               

fb/templates/fb-templates/craa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/creatnewacc.css' %}">
</head>

<body>
    <div class="container">
        <div class="header">
            <div class="logo">
                <a class="logo-text" href="index.html">facebook</a>
            </div>

        </div>

        <div class="body">
            <form action="">
            <div class="bhead">
              <h1>creat a new account</h1>
            </div>
            <div class="bp1">
                it,s free and always will be.

            </div>
            <div style="margin-left: 37%; margin-top: 2%;">
                <table>
                    <tr>
                        <td><input class="inpt" type="text" placeholder=" name"></td>
                        
                    </tr>
                    <tr>
                        <td >
                            <input class="inpt" type="text" placeholder="email or mobail no">
                        </td>
                    </tr>
                    <tr>
                        <td >
                            <input  class="inpt" type="password" placeholder="new password">
                        </td>
                    </tr>
                  
                </table>
                
            </div>
            <div class="dob"><h3>Birthday</h3></div>
            <div><input type="date" name="" class="dob" id="dobt"></div>
            <div style="margin-left: 37%; margin-top: 1%;">Mail<input type="radio" name="genter" id="">Femail
            <input type="radio" name="genter" id="" ></div>
            <div>
                <button style="margin-left: 40%; margin-top: 1%;" id="sbtn" type="submit">creat account</button>
            </div>

        </form>
        </div>


    </div>
</body>

</html>

fb/templates/fb-templates/forget.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/forget.css' %}">
</head>
<body>
    <div class="a">
        <div class="main1" style="background-image: {%  %}">
            <div class="h22"><h2>forget password!</h2></div>
            <div class="p1"><p>"enter the email address you used when you <br> joind and we will seand you instryctions to <br>reset your password"</p></div>
            <div class="i1"><input class="mail" type="email" placeholder="enter email"></div>
        </div>
    </div>
    
</body>
</html>

fb/templates/fb-templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>

<body style="margin: 0px;">
  <table style="height: 100%;width: 100%;">
    <td id="td1" align="center">
      <br><br><br><br>
      <table id="tb2">
        <tr style="height: 200px;">
          <th id="tb2th" colspan="3">
            faceboook

        </tr>

        <tr>
          <td width="35%"></td>
          <td class="p1">connect with </td>
        </tr>
        <tr>
          <td></td>
          <td class="p1">friends and thr</td>
            
        </tr>
        <tr>
          <td></td>
          <td class="p1">world around you </td>
            
        </tr>
        <tr style="height: 350px;">
          <td></td>
        </tr>




      </table>



    </td>
    <td align="center" style="width: 50%;">
      <table width="78%">
        
          <tr>
            <td id="login" align="center">

              <h3>log in</h3>
            </td>
          </tr>
          <tr>
            <td align="center"><input class="inp1" type="email" placeholder="user name or mail"> </td>
          </tr>
          <tr>
            <td align="center"><br><input class="inp1" type="password" placeholder="password"></td>
          </tr>
          <tr>
            <td align="center"> <br><a href="{% url 'fb:page' %}"><input id="subm" type="submit" value="log in"></a></td>
          </tr>
      
        <tr>
          <td align="center">
            <a href="{% url 'fb:forget' %}"><p style="font-size: small;">forgot password?</p></a>
          </td>
        </tr>
        <tr>
          <td align="center"><br><br><a href="{% url 'fb:craa' %}"><input id="sub" type="button" value="creat new account"></a></td>
        </tr>
        <tr>
          <td align="center">
            <p style="font-size: small;"> <b>creat a page</b> for a celebrity,band or business.</p>
          </td>
        </tr>

      </table>




    </td>
  </table>


</body>

</html>

fb/templates/fb-templates/page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/page.css' %}">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

</head>

<body style="margin: 0;">
<div >

    <div style="width: 100%;">
        <div class="p2">
            <div id="div1">
                <h2 id="h">facebook</h2>
            </div>
            <div class="div1"><span style="color: white; size: 30px;" class="material-symbols-outlined">
                    notifications
                </span></div>
            <div class="div1"><span style="color: white; size: 30px;" class="material-symbols-outlined">
                    newspaper
                </span></div>
            <div class="div1"><span style="color: white; size: 30px;" class="material-symbols-outlined">
                    live_tv
                </span></div>
            <div class="div1"><span style="color: white; size: 30px;" class="material-symbols-outlined">
                    account_circle
                </span></div>
        </div>
    </div>

    <div class="maindiv2">

        <div id="div2_1">
            
            <div id="navi2">

                <input id="inp" type="search" placeholder="serche">

            </div>
            <br>
            <table style="width: 100%; ">
                <tr class="tr1">
                    <td><img style="width: 35px; border-radius: 35px;" src="{% static 'image/images.jpeg' %}" alt="">
                    </td>
                    <td class="td2">messi</td>
                </tr>
                <tr class="tr1">
                    <td class="td1"><span class="material-symbols-outlined">
                            diversity_3
                        </span></td>
                    <td class="td2">friends</td>
                </tr>
                <tr class="tr1">
                    <td class="td1"><span class="material-symbols-outlined">
                            reviews
                        </span></td>
                    <td class="td2">messanger</td>
                </tr>
                <tr class="tr1">
                    <td class="td1"><span class="material-symbols-outlined">
                            flag
                        </span></td>
                    <td class="td2">pages</td>
                </tr>
                <tr class="tr1">
                    <td class="td1"><span class="material-symbols-outlined">
                            local_convenience_store
                        </span></td>
                    <td class="td2">marketplace</td>
                </tr>
                <tr class="tr1">
                    <td class="td1"><span class="material-symbols-outlined">
                            live_tv
                        </span></td>
                    <td class="td2">videos</td>
                </tr>
                <tr class="tr1">
                    <td class="td1"><span style="color: rgb(156, 80, 33); " class="material-symbols-outlined">
                            celebration
                        </span></td>
                    <td class="td2">events</td>
                </tr>

            </table>
        </div>
        <div id="div2_2">
            <div class="para"><br>
                <div class="child">
                    <div class="idd">
                        <div class="imgg"><img style="width: 50px;border-radius: 40px;" src="{% static 'image/ronodp.jpeg' %}" alt=""></div>
                        <div class="namee"> Cristiano Ronaldo</div>

                    </div>
                    <div><img style="width: 500px;" src="{% static 'image/ronopost.jpeg' %}" alt=""> </div>
                </div><br>
                <div class="child">
                    <div class="idd">
                        <div class="imgg"><img style="height: 50px;width: 50px;border-radius: 40px;" src="{% static 'image/Ardp.jpeg' %}" alt=""></div>
                       
                        <div class="namee"> Antonella Roccuzzo
                        </div>
                    </div>
                    <div><img style="width: 500px;" src="{% static 'image/msg.jpeg' %}" alt=""></div>
                </div><br>
                <div class="child">
                    <div class="idd">
                        <div class="imgg"><img style="width: 50px; border-radius: 40px;" src="{% static 'image/njdp.jpeg' %}" alt=""></div>
                        <div class="namee"> Neymar</div>
                    </div>
                    <div><img style="width: 500px;" src="{% static 'image/njpost.jpeg' %}" alt=""></div>
                </div><br>
              
            </div>
        </div>

    </div>

   </div> 



</body>

</html>